### PR TITLE
added timetout to force error when gps is disable

### PR DESCRIPTION
**Pull request by caio-ribeiro-pereira**
I added timetout of 10 seconds into option var, to force error when gps is disable.
Take a look: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation#Fine_tuning_response

### CODE REVIEW

**Comment by caio-ribeiro-pereira** [comment]
Please, I hope you can accept this PR soon, because I really need this patch into my app http://99folks.com

**Comment by stubailo** [comment]
Hi, sorry I didn't notice - thanks for reminding. Please sign the agreement here: https://contribute.meteor.com/

**Comment by caio-ribeiro-pereira** [comment]
Done! Thanks a lot! And please let me know when this patch will be available on atmosphere. See ya!

**Comment by caio-ribeiro-pereira** [comment]
Nice!

**Comment by stubailo** [comment]
published as 1.0.3, thanks!

**Comment by caio-ribeiro-pereira** [comment]
Thanks a lot!

**Pull request merged**
