### PR TITLE
#21 clarify extra camera options

### PR DESCRIPTION
**Pull request by KristerV**
Added essential option (correctOrientation) and link to all the other options that are available.

### CODE REVIEW

**Comment by KristerV** [comment]
should work even better with 9c9661f28e1894d38ae6873c552495a483a09366

**Comment by stubailo** [comment]
Can we add a note that these options are Cordova-only? (they won't work on desktop or mobile web)

**Comment by KristerV** [comment]
good idea - added notes.

**Comment by KristerV** [comment]
from 4 years ago? okay.. closing.

**Pull request closed without merging**
