### PR TITLE
Update simple map example & add open street map example

### PR DESCRIPTION
**Pull request by StorytellerCZ**
* Update to latest Meteor version
* Add latitute and longtitute details, so that the data shows even if maps are not configured with API keys
* Add Geoapify to show OpenStreetMap map example

### CODE REVIEW

**Review by filipenevola — CHANGES_REQUESTED** [review]
What you think about moving examples to our main examples repo and deploy them for free on Galaxy?

**Comment by StorytellerCZ** [comment]
I'm for deploying them (though the third example needs update, there is already an issue about this). I don't think we necessarily need to move them to the examples repo and instead just link here, but if we want to centralize and ensure that the examples there are always deployed properly then I'm fine with that.

**Comment by StorytellerCZ** [comment]
I will locally create the maps app with keys (so that they work), deploy it and then add a link to examples repo to start with.

**Review by filipenevola — APPROVED** [review]
Please remember to deploy and link in the main examples repo.

**Pull request merged**
