### PR TITLE
Update solomo example

### LINKED ISSUE #124: Update and upgrade
Can you redo this for the latest meteor version. 1.4 at the moment?

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Fix #124 
Updates Solomo example to the latest Meteor version.

### CODE REVIEW

**Review by filipenevola — APPROVED** [review]

**Review by filipenevola — CHANGES_REQUESTED** [review]
The readme of this example needs some attention as well.

For example, it's linking to a HackPad that doesn't exist anymore.

Is the app working properly with latest Meteor?

**Comment by StorytellerCZ** [comment]
Yes, I have tested it with 2.4. I'll give the readme some love tomorrow and get a deploy on Galaxy.

**Comment by StorytellerCZ** [comment]
Published demo on: https://solomo.meteorapp.com/

**Review by filipenevola — APPROVED** [review]
We could improve the way to display the images, keep proportion, etc. but it's working good in a cellphone

**Pull request merged**
