### PR TITLE
#45 Clarify where Camera can be used

### PR DESCRIPTION
**Pull request by KristerV**

### CODE REVIEW

**Comment by stubailo** [comment]
The main goal of this package is to also work in desktop browsers (although I'm aware the implementation is not perfect) - otherwise, you could just use the Cordova plugin directly.

**Comment by KristerV** [comment]
ooh, I see. let me think about this..

**Comment by stubailo** [comment]
Yeah, which is definitely a feature we should have

**Comment by KristerV** [comment]
okay. So the black sheep is basically the mobile browser. Do I understand correctly, that `if (mobileBrowser) { use <input type="file" accept="image/*" capture="camera" /> }` would do the job just fine?

**Pull request closed without merging**
